### ISSUE TITLE
fails in windows

### ISSUE THREAD

**Issue by rdp** [headius/bitescript#7]
http://groups.google.com/group/mirah/browse_thread/thread/acaa776a926cb3b0

$ jruby -S mirah -e 'puts "Hello, Mirah!"'
RuntimeError: Unknown opcode: MH_INVOKESPECIAL
    Bytecode at G:/dev_d/ruby/downloads/jruby/lib/ruby/gems/1.8/gems/
bitescript-0.0.8/lib/bitescript/bytecode.rb:313 
...

**Comment by baroquebobcat** [comment]
Do you still have this issue when running bitescript from git?

**Comment by rdp** [comment]
oops my bad, seems to work fine from git. Looking forward to the next release :)

-roger-
